CREATE TABLE `prueba_sql`.`tecnicos_unicos` (
  `CEDULA TECNICO REAL` INT NOT NULL,
  `NOMBRE TECNICO REAL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CEDULA TECNICO REAL`)
);
INSERT INTO `prueba_sql`.`tecnicos_unicos` (`CEDULA TECNICO REAL`, `NOMBRE TECNICO REAL`)
SELECT DISTINCT `CEDULA TECNICO REAL`, `NOMBRE TECNICO REAL`
FROM `prueba_sql`.`julio_dia01`;

CREATE TABLE `coordinadores` (
  `ID_COORDINADOR` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_COORDINADOR` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_COORDINADOR`)
);
INSERT INTO `prueba_sql`.`coordinadores` (`NOMBRE_COORDINADOR`)
SELECT DISTINCT `COORDINADOR`
FROM `prueba_sql`.`julio_dia01`;